name: datasim
channels:
  - conda-forge
  - defaults
dependencies:
  # pin only high-level things
  - python=3.13
  - pip
  - ipykernel=6.30.1
  - ipython=9.5.0
  - jupyter_client=8.6.3
  - jupyter_core=5.8.1
  - numpy=2.3.*
  - pandas=2.3.*
  - scipy=1.16.*
  - pyzmq=27.1.0
  - psutil=7.0.0
  - tornado=6.5.2
  - traitlets=5.14.3
  - packaging=25.0
  - matplotlib-inline=0.1.7
  - ca-certificates
  - openssl
  - sqlite
  - libffi
  - bzip2
  - xz
  - zlib
  - expat
  - krb5
  - libsodium
  - tk
  # (removed: appnope, ncurses, readline, _python_abi3_support, python-gil, python_abi, cpython)
  - pip:
      - accessible-pygments==0.0.5
      - alabaster==1.0.0
      - altair==5.5.0
      - ansicolors==1.1.8
      - attrs==25.3.0
      - babel==2.17.0
      - beautifulsoup4==4.13.4
      - blinker==1.9.0
      - cachetools==6.1.0
      - certifi==2025.8.3
      - charset-normalizer==3.4.3
      - choreographer==1.0.10
      - click==8.2.1
      - coverage==7.10.5
      - docutils==0.21.2
      - flake8==7.3.0
      - flatdict==4.0.1
      - furo==2025.7.19
      - gitdb==4.0.12
      - gitpython==3.1.45
      - idna==3.10
      - imagesize==1.4.1
      - iniconfig==2.1.0
      - jinja2==3.1.6
      - jsonschema==4.25.1
      - jsonschema-specifications==2025.4.1
      - kaleido==1.0.0
      - logistro==1.1.0
      - markupsafe==3.0.2
      - mccabe==0.7.0
      - narwhals==2.1.2
      - nodeenv==1.9.1
      - numpy==2.3.2
      - ordered-set==4.1.0
      - orjson==3.11.2
      - pandas==2.3.2
      - pandas-stubs==2.3.0.250703
      - pillow==11.3.0
      - plotly==6.3.0
      - pluggy==1.6.0
      - protobuf==6.32.0
      - pyarrow==21.0.0
      - pycodestyle==2.14.0
      - pydeck==0.9.1
      - pydocstyle==6.3.0
      - pyflakes==3.4.0
      - pyright==1.1.404
      - pytest==8.4.1
      - pytest-cov==6.2.1
      - pytest-md==0.2.0
      - pytz==2025.2
      - pyyaml==6.0.2
      - referencing==0.36.2
      - requests==2.32.5
      - roman-numerals-py==3.1.0
      - rpds-py==0.27.0
      - scipy==1.16.1
      - simplejson==3.20.1
      - smmap==5.0.2
      - snowballstemmer==3.0.1
      - soupsieve==2.7
      - sphinx==8.2.3
      - sphinx-basic-ng==1.0.0b2
      - sphinxcontrib-applehelp==2.0.0
      - sphinxcontrib-devhelp==2.0.0
      - sphinxcontrib-htmlhelp==2.1.0
      - sphinxcontrib-jsmath==1.0.1
      - sphinxcontrib-qthelp==2.0.0
      - sphinxcontrib-serializinghtml==2.0.0
      - streamlit==1.48.1
      - tenacity==9.1.2
      - toml==0.10.2
      - tzdata==2025.2
      - urllib3==2.5.0
      - webcolors==24.11.1
